<a href="https://colab.research.google.com/github/chuviethongfpt/streamlit.io/blob/main/Googlecolab/Market_Basket_Analysis_Freeuser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementing market basket analysis

In [ ]:
#Loading neccesary packages
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
#Reading Data From Web
order_df = pd.read_csv('order_processed.csv')
order_df.head()

   OrderID Transaction Date  UserID Bill Type  Total Amount
0     6706        8/16/2020   44822       VIP        199000
1     6998        8/23/2020   47128       VIP        199000
2     6927        8/21/2020   47134       VIP        199000
3     7054        8/25/2020   45972       VIP        199000
4     6929        8/21/2020   43556       VIP        199000

In [ ]:
user_df = pd.read_csv('user_processed.csv')
user_df.head()

   UserID VIP hay Free  ... Total Listerning  Total Listening Time (Min)
0   86229         free  ...              218                      4151.3
1   48053         free  ...               19                       278.6
2   46340         free  ...               28                       170.5
3   66659         free  ...              345                      6721.4
4   59396         free  ...               23                        52.5

[5 rows x 11 columns]

In [ ]:
listen_df = pd.read_csv('listening_processed.csv')
listen_df.head()

   PlaylistID (PK)  ... Unnamed: 11
0             4529  ...         NaN
1             4577  ...         NaN
2             4169  ...         NaN
3             4581  ...         NaN
4             4577  ...         NaN

[5 rows x 12 columns]

In [ ]:
order_df1 = order_df.groupby(['UserID'], as_index=False).sum()
order_df1.head()

   UserID  OrderID  Total Amount
0   40843     2544         27000
1   40861     7707        199000
2   41003     9599        599000
3   41014    15326        398000
4   41057     9313        599000

In [ ]:
order_df2 = order_df1.loc[order_df1['Total Amount'] > 199000]
order_df2.head()

    UserID  OrderID  Total Amount
2    41003     9599        599000
3    41014    15326        398000
4    41057     9313        599000
6    41133     7039        599000
10   41485    17236        318000

In [ ]:
playlist_df = listen_df.merge(order_df2,how='inner',on='UserID',)
playlist_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 139577 entries, 0 to 139576
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   PlaylistID (PK)          139577 non-null  int64
 1   Playlist Name            139577 non-null  object
 2   Category                 139577 non-null  object
 3   Sub Category             139577 non-null  object
 4   Playlist Type            139577 non-null  object
 5   Playlist Duration (min)  139577 non-null  float64
 6   Actual Duration (min)    139577 non-null  float64
 7   UserID                   139577 non-null  int64
 8   Listening Time           139577 non-null  object
 9   Listening Date           139577 non-null  object
 10  Listening Datetime       139577 non-null  object
 11  Unnamed: 11              0 non-null       float64
 12  OrderID                  139577 non-null  int64
 13  Total Amount             139577 non-null  int64
dtypes: float64(3), int64(4), object(7)
memory usage: 16.0+ MB

In [ ]:
playlist_df.head()

   PlaylistID (PK)                     Playlist Name  ... OrderID Total Amount
0             4595  Đội Thiếu Niên Du Kích Thành Huế  ...   12499       280000
1             4595  Đội Thiếu Niên Du Kích Thành Huế  ...   12499       280000
2             5136              Hạt Giống Tâm Hồn 12  ...   12499       280000
3             5136              Hạt Giống Tâm Hồn 12  ...   12499       280000
4             5136              Hạt Giống Tâm Hồn 12  ...   12499       280000

[5 rows x 14 columns]

In [ ]:
cluster_df = pd.read_csv('clustering_processed.csv')
cluster_df.head()

   UserID Type_user  MainCluster_ID MainCluster_Description
0   40834      free               1             Hibernating
1   40854      free               1             Hibernating
2   40876      free               1             Hibernating
3   40883      free               1             Hibernating
4   40891      free               1             Hibernating

In [ ]:
cluster_list = ['Potential, Skimming Listeners','Potential, Engaging Listeners', 'Loyal Users, Skimming Listeners', 'Loyal Users, Engaging Listeners']
cluster_df2 = cluster_df[cluster_df['MainCluster_Description'].isin(cluster_list)]
cluster_df2

       UserID Type_user  MainCluster_ID          MainCluster_Description
10283   58703      free               9  Loyal Users, Skimming Listeners
10284   72584      free               9  Loyal Users, Skimming Listeners
10285   73695      free               9  Loyal Users, Skimming Listeners
10286   82542      free               9  Loyal Users, Skimming Listeners
10287   83037      free               9  Loyal Users, Skimming Listeners
...       ...       ...             ...                              ...
24815  105771      free               8    Potential, Engaging Listeners
24816  106143      free               8    Potential, Engaging Listeners
24817  106344      free               8    Potential, Engaging Listeners
24818  106646      free               8    Potential, Engaging Listeners
24819   96022      free               8    Potential, Engaging Listeners

[3481 rows x 4 columns]

In [ ]:
df9 = user_df.merge(abc,how='inner',on='UserID')
df9.head()

In [ ]:
free_df = listen_df.merge(cluster_df2,how='inner',on='UserID')
free_df

        PlaylistID (PK)  ...        MainCluster_Description
0                  4529  ...  Potential, Engaging Listeners
1                  4563  ...  Potential, Engaging Listeners
2                  4563  ...  Potential, Engaging Listeners
3                  4563  ...  Potential, Engaging Listeners
4                  4529  ...  Potential, Engaging Listeners
...                 ...  ...                            ...
162078             4929  ...  Potential, Engaging Listeners
162079             4929  ...  Potential, Engaging Listeners
162080             4929  ...  Potential, Engaging Listeners
162081             4929  ...  Potential, Engaging Listeners
162082             4929  ...  Potential, Engaging Listeners

[162083 rows x 15 columns]

In [ ]:
free_df2 = free_df[['UserID','Playlist Name']]
free_df2

        UserID                        Playlist Name
0        82846        Dạy Tiếng Anh Cho Trẻ Mầm Non
1        82846  Bí Kíp Nói Tiếng Anh Như Tiếng Việt
2        82846  Bí Kíp Nói Tiếng Anh Như Tiếng Việt
3        82846  Bí Kíp Nói Tiếng Anh Như Tiếng Việt
4        82846        Dạy Tiếng Anh Cho Trẻ Mầm Non
...        ...                                  ...
162078  100631            Hành Trình Về Phương Đông
162079  100631            Hành Trình Về Phương Đông
162080  100631            Hành Trình Về Phương Đông
162081  100631            Hành Trình Về Phương Đông
162082  100631            Hành Trình Về Phương Đông

[162083 rows x 2 columns]

In [ ]:
df2=free_df2.values.tolist()

In [ ]:
from collections import defaultdict
d = defaultdict(list)
for k, v in df2:
    d[k].append(v)
for k in d:
  d[k] = list(set(d[k]))

In [ ]:
df2 = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in d.items() ]))
df2 = df2.transpose()
df2

                                               0    ...  165
82846   [Sách Tóm Tắt] Đừng Bao Giờ Đi Ăn Một Mình  ...  NaN
94362                    Này Cô Gái, Thức Tỉnh Đi!  ...  NaN
64413                           Thu Hà - Mẹ Xu Sim  ...  NaN
56704                   Bác Gấu Đen Và Hai Chú Thỏ  ...  NaN
90116                                Tâm Sự Yêu Xa  ...  NaN
...                                            ...  ...  ...
90263             Nhạc Tập Trung Làm Việc, Học Tập  ...  NaN
104598                      Nhìn Cuộc Sống Khác Đi  ...  NaN
98863                  Muôn Kiếp Nhân Sinh - Tập 1  ...  NaN
96380                         Hạt Giống Tâm Hồn 12  ...  NaN
100631                   Hành Trình Về Phương Đông  ...  NaN

[3481 rows x 166 columns]

In [ ]:
from mlxtend.preproces import TransactionEncoder

te = TransactionEncoder()
onehot = te.fit_transform(d.values())
onehot = pd.DataFrame(onehot, columns = te.columns_)

In [ ]:
onehot

       Bé Gấu 5 Tuổi Đã Dạy Tôi Những Gì  ...  Ứng Dụng Thành Công NLP
0                                  False  ...                    False
1                                  False  ...                    False
2                                  False  ...                    False
3                                  False  ...                    False
4                                  False  ...                    False
...                                  ...  ...                      ...
3476                               False  ...                    False
3477                               False  ...                    False
3478                               False  ...                    False
3479                               False  ...                    False
3480                               False  ...                    False

[3481 rows x 1086 columns]

In [ ]:
frequent_itemsets=apriori(onehot, min_support=0.005 use_colnames=True, max_len=3)
frequent_itemsets

       support                                           itemsets
0     0.011491  ( Triết - Đức Phật Thuyết Giảng Về Tánh Không ...
1     0.006033                               ( Đồng Dao Cho Bé 2)
2     0.007182                               ( Đồng Dao Cho Bé 3)
3     0.006033                 (10 Bí Quyết Của Các MC, Diễn Giả)
4     0.046826                            (10 Quy luật cuộc sống)
...        ...                                                ...
1514  0.005171  (Trời Tính Không Bằng Trời Tính , Tâm Lý Học, ...
1515  0.008618  (Trời Tính Không Bằng Trời Tính , Đừng Bao Giờ...
1516  0.005171  (Tư Duy Tích Cực - Bạn Là Những Gì Bạn Nghĩ (N...
1517  0.005745  (Đừng Bao Giờ Từ Bỏ Ước Mơ, Đắc Nhân Tâm, Thái...
1518  0.005171         (Thánh Gióng, Ăn Khế Trả Vàng, Thạch Sanh)

[1519 rows x 2 columns]

In [ ]:
rules=association_rules(frequent_itemsets)
rules

                                antecedents  ... conviction
0        (Chưa Đỗ Ông Nghè Đã Đe Hàng Tổng)  ...   8.268697
1                        (Cây Tre Trăm Đốt)  ...   5.361218
2           (Gốc Tích Bánh Chưng Bánh Giầy)  ...  10.921000
3     (Gốc Tích Bộ Lông Quạ & Bộ Lông Công)  ...  11.417409
4        (Chưa Đỗ Ông Nghè Đã Đe Hàng Tổng)  ...   6.208704
...                                     ...  ...        ...
1130    (Ăn Khế Trả Vàng, Sự Tích Trầu Cau)  ...   6.201523
1131         (Thạch Sanh, Sự Tích Trầu Cau)  ...  21.810399
1132         (Thánh Gióng, Ăn Khế Trả Vàng)  ...        inf
1133              (Thánh Gióng, Thạch Sanh)  ...        inf
1134                          (Thánh Gióng)  ...   6.949727

[1135 rows x 9 columns]

In [ ]:
rules['antecedent'] = rules['antecedents'].apply(lambda antecedent: list(antecedent))
rules['consequent'] = rules['consequents'].apply(lambda consequent: list(consequent))
coords1 = rules[['antecedent','consequent']]

In [ ]:
from google.colab import files
coords1.to_csv('none.csv')
files.download('none.csv')

# FREE (18-24)

In [ ]:
dfh = user_df.merge(free_df,how='inner',on='UserID (FK)')
dfh.head()

In [ ]:
user_list = ['18 - 24']
user_df3 = dfh[dfh['Age Range'].isin(user_list)]
user_df3

In [ ]:
dfh1 = listen_df.merge(user_df3,how='inner',on='UserID (FK)')
dfh1.head()

# Free 25 - 34

# Free 35 - 44